language: python
python:
- '2.7'

install:
  - pip install gitpython

script:
  - cd _tools/
  - travis_retry python create_repo.py 2
  - cd ..
  - git clean -f -d
  - git reset && ls
  - cd _tools/
  - travis_retry python create_repo.py 3

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master   
